### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by WenXin20** [nikita488/ZYCraft#1]
`Minecraft v1.15.2`
`Forge v31.2.31`
`CTM v1.1.0.10`
`ZYCraft v0.0.3`

Most block underlays are not displaying properly, both when placed and in the inventory, as seen in the screenshot. And aluminium ore is using the old stone texture.
![2020-07-17_14 07 49](https://user-images.githubusercontent.com/12000593/87822708-906c6200-c837-11ea-98b8-350ee980446a.png)

**Comment by nikita488** [comment]
Can you post your log file (latest.log) on pastebin.com?

**Comment by WenXin20** [comment]
I forgot to mention that this is on a server. I also don't see anything in the log, but here it is:
https://gist.github.com/WenXin20/7dacfda88562e9ab013d6fd9449463cc
I also noticed that Aluminium is missing the forge tag `forge:ingots/aluminium`

**Comment by WenXin20** [comment]
Here is the client log, this has some errors from the mod:
https://gist.github.com/WenXin20/8bcac5ffc69c25431689da436c95e087

**Comment by nikita488** [comment]
Can you try to run a modpack only with Forge, CTM and ZYCraft and see if the problem still exist? Because for some reason it works just fine on my end...

**Comment by WenXin20** [comment]
Looks like this is being caused by the preview version of Optifine

**Comment by nikita488** [comment]
Aluminium Ore texture will be fixed in the next release.
As for ingots/aluminium tag, right now it's intended because my Aluminium is not like ingot and it will be strange if i you will be able to craft Aluminium Block's from my mod using ingots from other tech-mod. And craft metal-like aluminium storage blocks from other tech-mod using my Aluminium. Maybe i will change that in the future.

**Comment by WenXin20** [comment]
Were you able to replicate the bug with Optifine?

**Comment by nikita488** [comment]
I will try tomorrow. But actually this is not surprising, Optifine is famous for breaking other mods (especially  rendering) and I can not do anything about it.

**Comment by WenXin20** [comment]
Yeah, I thought that might be the case. Optifine was the first mod I tested to find the incompat.

**Comment by nikita488** [comment]
Yeah, tested with Optifine and I get missing textures on my blocks, so nothing I can do about this. I will add a warning on the Curseforge page.
Also, Aluminium Ore texture was fixed, update mod to 0.0.4.

**Comment by nikita488** [comment]
@WenXin20 I fixed Optifine incompatibility in 0.0.6.

**Comment by WenXin20** [comment]
Oh, thanks!
