### ISSUE TITLE
XRay Texture

### ISSUE THREAD

**Issue by LazerusKI** [nikita488/ZYCraft#13]
Minecraft v1.16.4
Forge v35.1.13
ZYCraft v2.0.1

https://www.youtube.com/watch?v=rEZC9TV_BKw
As you can see in that Video, the shiny texture is only visible in a circle around the player.
Outside of that, it behaves like an XRay.
No Optifine installed,

**Comment by nikita488** [comment]
Does this happen if only Forge, CTM and ZYCraft installed?

**Comment by LazerusKI** [comment]
Sorry for the late response, took some time to find the culprit.

Seems like it is a conflict with the "Performant" Mod https://www.curseforge.com/minecraft/mc-mods/performant
and to be more specific, the "Clientside FPS improvement"

Not sure whose problem it is now as i dont know how the FPS improvement or your textures work

**Comment by mcquestion** [comment]
Heyo, me and a friend are having the same issue with Optifine. We've noticed it only happens on some blocks (Light Zychromium Bricks) but not others, are these blocks classed differently in some way that could be causing it? Like if they're classed the same as glass or something?

**Comment by nikita488** [comment]
I don't do anything special except injecting Animation of blocks, so it probably will not work well with Optifine or other performance improvement mods (because they usually break a lot of rendering in the mods).

**Comment by mcquestion** [comment]
Hey, thanks for the quick reply! Is there some way I could disable the animations and make them static? The animations on the ores seem to be fine but it's mostly the Light Zy Bricks

**Comment by nikita488** [comment]
My blocks can be customized using resource packs like any other Minecraft blocks :) But there is no way to make my animation static, you will need to replace the texture on the problem blocks.

**Comment by mcquestion** [comment]
Heyo man, just been working a bit more on our server and found even more problems with Optifine and other mods so we're going to remove Optifine altogether. That should fix the textures. :) Sorry to have wasted your time at all with this, and thanks for being so helpful, friendly and quick to respond!

**Comment by nikita488** [comment]
No problem, it's fine :) Yeah, Optifine and other "performance improvement" mods are known for breaking the rendering of other mods, so if you have a small number of mods that don't have any fancy rendering, you can use Optifine. But if it's a large modpack that has a lot of mods, it's not recommended.
