### ISSUE TITLE
Texture problem 

### ISSUE THREAD

**Issue by adek1999922** [nikita488/ZYCraft#15]
![2021-07-18_13 57 04](https://user-images.githubusercontent.com/86684695/126066122-1093edcf-d6b9-4a61-aa9c-7482ece0e40f.png)
hey, I have a problem with zycraft, namely when I add to my modpack, the textures of the blocks disappear and I don't know what is the error, will anyone help?  
![2021-07-18_13 59 06](https://user-images.githubusercontent.com/86684695/126066160-e6fb9436-32c0-4b01-8e51-de9d93c546c8.png)

**Comment by nikita488** [comment]
Do you have Optifine installed? If so, remove it and try without it

**Comment by adek1999922** [comment]
yes

**Comment by nikita488** [comment]
Optifine is incompatible with a lot of mods that have a non-standard visual appearance.

**Comment by adek1999922** [comment]
ok. i remove optifine and I'll tell you if the problem is gone

**Comment by adek1999922** [comment]
that's how it caused me this problem. Attack a pro for this horror You get the imitation of Xycraft I'm a big fan. Xycraft was my favorite tank mod. Thanks again for your help

**Comment by adek1999922** [comment]
I have a question, is there any way to get around this problem to be zycraft and optifine?

**Comment by nikita488** [comment]
Sadly no, because Optifine replaces a lot of Minecraft rendering and there are no way to fix this on my end. Optifine should be installed only if you play without mods or if you play with lightweight mods that don't do complex rendering.
