### ISSUE TITLE
optifine no like ur mod and where discord>?

### ISSUE THREAD

**Issue by YumiComiusito** [nikita488/ZYCraft#16]
[crash-2021-08-18_12.53.52-client.txt](https://github.com/nikita488/ZYCraft/files/7009207/crash-2021-08-18_12.53.52-client.txt)

**Comment by nikita488** [comment]
Optifine is incompatible with a lot of mods that have a non-standard visual appearance. Optifine replaces a lot of Minecraft rendering and there is no way to fix this on my end. Optifine should be installed only if you play without mods or if you play with lightweight mods that don't do the complex rendering.
And I don't have a discord server for this mod.
