### ISSUE TITLE
[1.16.3] You have a dependency on curseforge for CTM-MC1.12.2-1.0.2.31 which is for 1.12.2

### ISSUE THREAD

**Issue by ProsperCraft** [nikita488/ZYCraft#4]
Installing ZYCraft downloads CTM for the wrong version of Minecraft.

**Comment by nikita488** [comment]
I think this is a bug on Curseforge right now because 1.15.2 version of my mod downloads 1.15 version of CTM just fine. It's not even possible to set the Required Dependency version, Curseforge doing it automatically so nothing I can do about it right now.

**Comment by nikita488** [comment]
CTM is now marked as 1.16.3, so my mod should download the proper version now.
