### ISSUE TITLE
Zycraft replacing Iron Ore world gen with Diamond Blocks

### ISSUE THREAD

**Issue by Darkfiend009** [nikita488/ZYCraft#6]
Minecraft: 1.16.3
Forge: 34.1.5
Zycraft: 0.1.3

I am creating a modpack and with Zycraft installed, all naturally generated vanilla iron ore is replaced with blocks of diamond.

![diamond](https://user-images.githubusercontent.com/42146629/94995801-a94efe80-056e-11eb-8c4c-650cc2322982.jpg)

**Comment by nikita488** [comment]
Oh jesus, I'm sorry about that! I forgot to remove debug worldgen json files in a release version.
Fixed in 0.1.4. Sorry!
