### ISSUE TITLE
1.16.4 crash on worldgen

### ISSUE THREAD

**Issue by jamzam90** [nikita488/ZYCraft#9]
Forge: 35.1.1
Zycraft: 1.16.3 1.1.1

[crash-2020-11-29_03.45.26-server.txt](https://github.com/nikita488/ZYCraft/files/5612291/crash-2020-11-29_03.45.26-server.txt)
Crashes when trying to generate clusters.

**Comment by nikita488** [comment]
Did you changed something inside config for worldgen?

**Comment by jamzam90** [comment]
Configs are the default.

**Comment by nikita488** [comment]
Should be fixed in the latest version.

**Comment by jamzam90** [comment]
Thank you,
